### ISSUE TITLE
Pretrained ImageNet weights for TF?

### ISSUE THREAD

**Issue by DrJimFan** [jyh2986/Active-Shift#1]
Hi,

Would you mind sharing your pretrained ImageNet weights for Tensorflow? It's difficult to port caffe weights to TF, especially when you have custom C++ layers. 

Thank you so much!

**Comment by jyh2986** [comment]
Hi, I'm sorry but I'm also unfamiliar with transferring weights from Caffe to TF.
If I have a chance to learn it, I will try. But I cannot assure.
Thanks.
